python infer.py \
    --lora_weight "models/age_slider.pt" \
    --scales "1,2,3,4" \
    --prompts "A selfie of a girl, upper body, smiling, beautiful" \
    --output_dir "output" \
    --pretrained_model "stablediffusionapi/realistic-vision-v51" \
    --device "cpu" \
    --num_images_per_prompt 1 \
    --negative_prompt "gray, blackwhite, nude, naked, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, distorted, ugly" \
    --batch_size 1 \
    --height 512 \
    --width 512 \
    --ddim_steps 50 \
    --guidance_scale 7.5
